baseURL = "https://iams1am.github.io/bracu-alter-site/"
languageCode = "en-us"
title = "BRACU ALTER"
theme = "alter"

[params]
  description = "BRAC University Autonomous Lab Team for Engineering & Robotics"
